server:
  port: 8081

spring:
  security:
    user:
      name: sa
      password: sa

eureka:
  client:
    service-url:
      defaultZone: http://pc-space1.ddns.net:8082/eureka
      registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true